### ISSUE TITLE
Can't access menu in VR mode

### ISSUE THREAD

**Issue by ChrisR1701** [Patrick-van-Halm/dv-multiplayer-mod#2]
When using the "Home" button to try and access to menu, it triggers the recentre menu when in SteamVR mode. After removing the keybind, the "Home" button still doesn't bring up the menu.

I have tried using the built in keyboard on Virtual Desktop and also directly from my PC.

I have an Oculus Quest 2 and use virtual desktop to launch SteamVR and then Derail Valley from there

**Comment by Patrick-van-Halm** [comment]
I will work on this after the name tags. So VR should be supported at least at the end of the week.
