### ISSUE TITLE
Multiplayer Client Can't Join V1.3.4

### ISSUE THREAD

**Issue by mattfleaydaly** [Patrick-van-Halm/dv-multiplayer-mod#54]
Client joins to message "Loading Save File" which never loads.
Logs don't show any error, they do show the client hitting the server so port forwarding is correct.
Current game version 29/04/2021 running Windows 10

**Comment by griffblob** [comment]
Yeah I am having the same issue. Just sits on 'Loading Save game' can only get out of it by restarting the game.

**Comment by Patrick-van-Halm** [comment]
Can I still get logs. Since these do show what the loading state is.

**Comment by griffblob** [comment]
[13-58-45-746.log](https://github.com/Patrick-van-Halm/dv-multiplayer-mod/files/6405151/13-58-45-746.log)
[14-07-44-437.log](https://github.com/Patrick-van-Halm/dv-multiplayer-mod/files/6405189/14-07-44-437.log)
One is the log of trying to connect on a local network the other is through the internet.

**Comment by Patrick-van-Halm** [comment]
Found the issue. Seems like there are no plugins being loaded. I updated the version here on git and on Nexus to contain the plugins this was an issue on my behalf.

**Comment by griffblob** [comment]
[14-31-42-522.log](https://github.com/Patrick-van-Halm/dv-multiplayer-mod/files/6405365/14-31-42-522.log)
now it shows the plugins loading but the other player still gets stuck on 'Loading SaveGame'

**Comment by griffblob** [comment]
Ok hosting it on the other computer worked. Thanks so much for the help
